// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTkQ0R8MnC64P4hRwBoSHW7hqqcpoI3SU',
    appId: '1:26765287051:web:6f32f58473eda3bfd27e8e',
    messagingSenderId: '26765287051',
    projectId: 'mini-app-firebase-f7514',
    authDomain: 'mini-app-firebase-f7514.firebaseapp.com',
    storageBucket: 'mini-app-firebase-f7514.firebasestorage.app',
    measurementId: 'G-E8ZTSVNY0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKvi-jD1V1NXDMuIjYML1HLD-q1et92k',
    appId: '1:26765287051:android:9d9b5652fc32c0ccd27e8e',
    messagingSenderId: '26765287051',
    projectId: 'mini-app-firebase-f7514',
    storageBucket: 'mini-app-firebase-f7514.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwCHXUcDz3l7kDTmqk3p2ngLSg27JQPU',
    appId: '1:26765287051:ios:1dc76f94749f45dcd27e8e',
    messagingSenderId: '26765287051',
    projectId: 'mini-app-firebase-f7514',
    storageBucket: 'mini-app-firebase-f7514.firebasestorage.app',
    iosClientId: '26765287051-b671kl1k4lujpb2oco2j6ar7ac2e3mj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tononkiraVfl',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwCHXUcDz3l7kDTmqk3p2ngLSg27JQPU',
    appId: '1:26765287051:ios:1dc76f94749f45dcd27e8e',
    messagingSenderId: '26765287051',
    projectId: 'mini-app-firebase-f7514',
    storageBucket: 'mini-app-firebase-f7514.firebasestorage.app',
    iosClientId: '26765287051-b671kl1k4lujpb2oco2j6ar7ac2e3mj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tononkiraVfl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTkQ0R8MnC64P4hRwBoSHW7hqqcpoI3SU',
    appId: '1:26765287051:web:aa43c16ced836dcad27e8e',
    messagingSenderId: '26765287051',
    projectId: 'mini-app-firebase-f7514',
    authDomain: 'mini-app-firebase-f7514.firebaseapp.com',
    storageBucket: 'mini-app-firebase-f7514.firebasestorage.app',
    measurementId: 'G-P7TCFGWQ56',
  );
}
